apiVersion: v1
kind: Pod
metadata:
  name: nginx-demo
spec:
  volumes:
  - name: shared-data
    hostPath:
      path: /usr/share/nginx/html
      type: Directory
  containers:
  - name: nginx-demo
    image: nginx:latest
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  hostNetwork: true
  dnsPolicy: Default